# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Visualizing the Future Symposia
tagline:          'An IMLS-funded National Forum on Data Visualization in Libraries (RE-73-18-0059-18)'
description:      'An IMLS-funded National Forum on Data Visualization in Libraries<br/>(RE-73-18-0059-18)'
url:              http://hyde.getpoole.com
baseurl:          https://visualizingthefuture.github.io/
#baseurl:          '/' # needed for local build

author:
  name:           'Visualizing the Future'
  url:            https://visualizingthefuture.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/visualizingthefuture/visualizingthefuture.github.io

# Google Analytics
google_analytics: UA-145226210-1

# Collections
collections:
  fellows:
    output: false
  projects:
    output: false
  resources:
    output: false
